### ISSUE TITLE
座席案内画面を作成

### ISSUE THREAD

**Issue by fukada6280** [ritscc/openhacku2022#61]

**Comment by averak** [comment]
@fukada6280 

座席案内画面ではなく、ログイン成功後は注文（ダッシュボード）画面に直接遷移し、ダイアログに席番号を出すと良いかと思います。

**Comment by fukada6280** [comment]
@averak 
なるほど、そっちの方が想像つきますね。
ということは注文画面を作成した後に作る必要があるから、座席番号表示の機能は後回しになりそうです。
