### ISSUE TITLE
「カメラを許可してください」の画像をAbelabのものに置換

### ISSUE THREAD

**Issue by fukada6280** [ritscc/openhacku2022#62]

**Comment by fukada6280** [comment]
Before
![image_access](https://user-images.githubusercontent.com/55773950/185385109-66d21ac1-7286-4337-b3aa-fa06b0bfe332.png)
After
![access](https://user-images.githubusercontent.com/55773950/185385170-83eb7f2d-6d0a-4f7b-8c83-61ae15806ed3.png)

**Comment by averak** [comment]
@fukada6280 
本URLはdev環境なので、prod環境（GCP）にデプロイすることを考えるとプロダクト名を入れたいですな。

**Comment by fukada6280** [comment]
@averak 
#75 でホーム画面を変更します。カメラ許可の画像は使わないことにします。
